"""Golden-master parity: the Python indicator layer must reproduce the TS
indicator math (frontend/src/lib/{mtf.ts,atr.ts,indicators/rsi.ts,indicators/vwap.ts})
exactly. The fixture is generated by frontend/src/lib/indicatorParityGolden.test.ts
— regenerate it there whenever the TS math changes."""

import json
import math
from datetime import datetime, timezone
from pathlib import Path

import pytest

from auto_trader.core.models import Candle
from auto_trader.indicators.core import (
    atr_series,
    avwap_series,
    ema_series,
    rsi_series,
    sma_series,
)

FIXTURE = Path(__file__).parent / "fixtures" / "indicator_golden.json"


@pytest.fixture(scope="module")
def golden():
    data = json.loads(FIXTURE.read_text())
    candles = [
        Candle(
            time=datetime.fromtimestamp(c["time"], tz=timezone.utc),
            open=c["open"], high=c["high"], low=c["low"], close=c["close"],
            volume=c["volume"],
        )
        for c in data["candles"]
    ]
    return candles, data["anchorMs"], data["series"]


@pytest.fixture(scope="module")
def golden_raw():
    return json.loads(FIXTURE.read_text())


def assert_series_equal(actual, expected, name):
    assert len(actual) == len(expected), f"{name}: length {len(actual)} != {len(expected)}"
    for i, (a, e) in enumerate(zip(actual, expected)):
        if e is None:
            assert a is None, f"{name}[{i}]: expected None, got {a}"
        else:
            assert a is not None, f"{name}[{i}]: expected {e}, got None"
            # Same float64 ops in the same order -> effectively identical;
            # rel=1e-12 only absorbs the JSON round-trip.
            assert a == pytest.approx(e, rel=1e-12, abs=1e-12), f"{name}[{i}]"


def test_ema(golden):
    candles, _, series = golden
    closes = [c.close for c in candles]
    assert_series_equal(ema_series(closes, 9), series["EMA_9"], "EMA_9")
    assert_series_equal(ema_series(closes, 21), series["EMA_21"], "EMA_21")


def test_sma(golden):
    candles, _, series = golden
    closes = [c.close for c in candles]
    assert_series_equal(sma_series(closes, 14), series["SMA_14"], "SMA_14")


def test_rsi(golden):
    candles, _, series = golden
    closes = [c.close for c in candles]
    assert_series_equal(rsi_series(closes, 14), series["RSI_14"], "RSI_14")


def test_atr(golden):
    candles, _, series = golden
    assert_series_equal(atr_series(candles, 14), series["ATR_14"], "ATR_14")


def test_volma(golden):
    candles, _, series = golden
    vols = [c.volume for c in candles]
    assert_series_equal(sma_series(vols, 20), series["VOLMA_20"], "VOLMA_20")


def test_avwap(golden):
    candles, anchor_ms, series = golden
    assert_series_equal(avwap_series(candles, anchor_ms), series["AVWAP"], "AVWAP")


def test_avwap_unplaced_anchor_is_blank(golden):
    candles, _, _ = golden
    assert avwap_series(candles, 0) == [None] * len(candles)
    # Anchor past the last bar -> all blank too.
    last_ms = int(candles[-1].time.timestamp() * 1000)
    assert avwap_series(candles, last_ms + 1) == [None] * len(candles)


def test_mtf_alignment(golden_raw):
    data = golden_raw
    base_times_ms = [c["time"] * 1000 for c in data["candles"]]
    htf = [
        Candle(
            time=datetime.fromtimestamp(c["time"], tz=timezone.utc),
            open=c["open"], high=c["high"], low=c["low"], close=c["close"], volume=c["volume"],
        )
        for c in data["htfCandles"]
    ]
    from auto_trader.indicators.mtf import align_htf_to_base

    htf_ema = ema_series([c.close for c in htf], 9)
    aligned = align_htf_to_base(base_times_ms, htf, htf_ema, 4 * 3600 * 1000)
    assert_series_equal(aligned, data["series"]["EMA_9@HOUR_4"], "EMA_9@HOUR_4")


def test_slope(golden):
    candles, _, series = golden
    from auto_trader.indicators.mtf import slope_of

    ema9 = ema_series([c.close for c in candles], 9)
    assert_series_equal(slope_of(ema9, 3, 1.0), series["EMA_9~3"], "EMA_9~3")


def test_edge_cases():
    assert ema_series([], 9) == []
    assert sma_series([1.0, 2.0], 0) == [None, None]
    assert rsi_series([1.0] * 5, 14) == [None] * 5  # n <= period -> all None
    assert atr_series([], 14) == []
