"""Golden-master parity: the Python slope pipeline must reproduce the TS math
(frontend/src/lib/indicators/slope.ts) exactly. The fixture is generated by
frontend/src/lib/indicators/slopeParityGolden.test.ts — regenerate it there
whenever the TS math changes."""

import json
import math
from datetime import datetime, timezone
from pathlib import Path

import pytest

from auto_trader.core.models import Candle
from auto_trader.indicators.slope import (
    SlopeConfig, accel_line_series, slope_line_series,
)

FIXTURE = Path(__file__).parent / "fixtures" / "slope_golden.json"


def _candles(rows):
    return [
        Candle(
            time=datetime.fromtimestamp(c["time"], tz=timezone.utc),
            open=c["open"], high=c["high"], low=c["low"], close=c["close"],
            volume=c["volume"],
        )
        for c in rows
    ]


@pytest.fixture(scope="module")
def golden():
    data = json.loads(FIXTURE.read_text())
    return {
        "clean": _candles(data["candles"]),
        "irregular": _candles(data["irregularCandles"]),
        "cases": data["cases"],
    }


def _smoothing(raw):
    return None if raw is None else (raw["type"], raw["length"])


def _cfg(c):
    return SlopeConfig(
        lengths=(c["length"],),
        ma_type=c["maType"],
        source=c["source"],
        slope_period=c["period"],
        units=c["units"],
        smoothing=_smoothing(c.get("smoothing")),
        show_accel=True,
        accel_period=c.get("accelPeriod", 3),
        accel_smoothing=_smoothing(c.get("accelSmoothing")),
        accel_absolute=c.get("accelAbsolute", False),
        timeframe=None,
    )


def test_every_case_matches(golden):
    assert golden["cases"], "fixture is empty — regenerate it"
    for case in golden["cases"]:
        candles = golden[case["series"]]
        cfg = _cfg(case["config"])
        fn = slope_line_series if case["kind"] == "slope" else accel_line_series
        actual = fn(candles, cfg, case["config"]["length"], case["barHours"])
        expected = case["values"]
        assert len(actual) == len(expected), case["name"]
        for i, (a, e) in enumerate(zip(actual, expected)):
            if e is None:
                assert a is None, f"{case['name']}[{i}]: expected None, got {a}"
            else:
                assert a is not None, f"{case['name']}[{i}]: expected {e}, got None"
                assert math.isclose(a, e, rel_tol=1e-12, abs_tol=1e-12), (
                    f"{case['name']}[{i}]: {a} != {e}"
                )


def test_fixture_is_non_vacuous(golden):
    for case in golden["cases"]:
        assert any(v is not None for v in case["values"]), case["name"]
