"""Bar-for-bar parity against the TypeScript detector.

The fixture is generated by
frontend/src/lib/indicators/candlePatternsGolden.test.ts — re-run that test to
regenerate it after changing the TS detector, then make this suite pass again.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime, timedelta
from pathlib import Path

from auto_trader.core.models import Candle
from auto_trader.indicators.candle_patterns import (
    CANDLE_PATTERN_DEFS,
    PATTERN_FNS,
    detect_all_patterns,
)

FIXTURE = Path(__file__).parent / "fixtures" / "candle_patterns_golden.json"
T0 = datetime(2026, 1, 1, tzinfo=UTC)

_STALE_FIXTURE = (
    "fixture has no `{key}` key — it predates this guard. Regenerate it with:\n"
    "  cd frontend && npx vitest run src/lib/indicators/candlePatternsGolden.test.ts"
)


def _load() -> tuple[list[Candle], list[list[str]]]:
    data = json.loads(FIXTURE.read_text())
    bars = [
        Candle(
            time=T0 + timedelta(minutes=i),
            open=b["open"], high=b["high"], low=b["low"], close=b["close"],
        )
        for i, b in enumerate(data["bars"])
    ]
    return bars, data["hits"]


def test_fixture_is_non_vacuous():
    """Guards against a fixture that silently stops exercising patterns."""
    _, expected = _load()
    fired = {pid for row in expected for pid in row}
    missing = sorted({d.id for d in CANDLE_PATTERN_DEFS} - fired)
    assert missing == [], f"fixture never fires: {missing}"


def test_every_bar_matches_the_typescript_detector():
    bars, expected = _load()
    actual = [sorted(s) for s in detect_all_patterns(bars)]
    assert len(actual) == len(expected)
    for i, (got, want) in enumerate(zip(actual, expected, strict=True)):
        assert got == want, f"bar {i}: python={got} typescript={want}"


def test_predicate_names_match_the_typescript_side():
    """Cross-stack name guard. The hit comparison above matches on pattern `id`
    only, so a renamed/added/dropped `fn` on either side would slip through:
    the rule editor would happily build an expression the backend then rejects.
    The fixture carries the TS predicate-name list so drift fails here instead.
    Regenerate via frontend/src/lib/indicators/candlePatternsGolden.test.ts.
    """
    data = json.loads(FIXTURE.read_text())
    assert "patternFns" in data, _STALE_FIXTURE.format(key="patternFns")
    assert data["patternFns"] == sorted(PATTERN_FNS)


def test_pattern_defs_match_the_typescript_side():
    """Cross-stack MEANING guard: id <-> fn <-> polarity, in order.

    The name guard above pins the predicate-name SET only, and the hit
    comparison pins pattern `id`s only. Neither says which detector output a
    given `fn` reads, nor which polarity it carries — yet on this side those
    two bindings ARE the rule semantics: PATTERN_FNS[fn] -> id decides which
    pattern `bullHarami(candle)` evaluates, and _BULL_IDS/_BEAR_IDS decide what
    bullPattern/bearPattern fire on. Swapping two `fn` labels or flipping one
    `polarity` silently changes every user's rule while leaving every other
    assertion in this repo green. Compared as an ordered list of dicts so a
    transposition of two adjacent defs fails, not just a missing one.

    Known limit (deliberate — this repo has no CI): the fixture is written BY
    the TS test, so a TS-side edit only surfaces here once someone regenerates
    it. What this genuinely closes is the Python-side edit, which now fails on
    the very next pytest run.

    Regenerate via frontend/src/lib/indicators/candlePatternsGolden.test.ts.
    """
    data = json.loads(FIXTURE.read_text())
    assert "patternDefs" in data, _STALE_FIXTURE.format(key="patternDefs")
    python = [{"id": d.id, "fn": d.fn, "polarity": d.polarity} for d in CANDLE_PATTERN_DEFS]
    assert data["patternDefs"] == python
