"""Golden-master parity: the Python indicator layer must reproduce the TS
indicator math (frontend/src/lib/{mtf.ts,atr.ts,indicators/rsi.ts,indicators/vwap.ts})
exactly. The fixture is generated by frontend/src/lib/indicatorParityGolden.test.ts
— regenerate it there whenever the TS math changes."""

import json
import math
from datetime import datetime, timezone
from pathlib import Path

import pytest

from auto_trader.core.models import Candle
from auto_trader.indicators.core import (
    atr_series,
    atr_smoothed_series,
    avwap_series,
    ema_series,
    rsi_series,
    sma_series,
)

FIXTURE = Path(__file__).parent / "fixtures" / "indicator_golden.json"


@pytest.fixture(scope="module")
def golden():
    data = json.loads(FIXTURE.read_text())
    candles = [
        Candle(
            time=datetime.fromtimestamp(c["time"], tz=timezone.utc),
            open=c["open"], high=c["high"], low=c["low"], close=c["close"],
            volume=c["volume"],
        )
        for c in data["candles"]
    ]
    return candles, data["anchorMs"], data["series"]


@pytest.fixture(scope="module")
def golden_raw():
    return json.loads(FIXTURE.read_text())


def assert_series_equal(actual, expected, name):
    assert len(actual) == len(expected), f"{name}: length {len(actual)} != {len(expected)}"
    for i, (a, e) in enumerate(zip(actual, expected)):
        if e is None:
            assert a is None, f"{name}[{i}]: expected None, got {a}"
        else:
            assert a is not None, f"{name}[{i}]: expected {e}, got None"
            # Same float64 ops in the same order -> effectively identical;
            # rel=1e-12 only absorbs the JSON round-trip.
            assert a == pytest.approx(e, rel=1e-12, abs=1e-12), f"{name}[{i}]"


def test_ema(golden):
    candles, _, series = golden
    closes = [c.close for c in candles]
    assert_series_equal(ema_series(closes, 9), series["EMA_9"], "EMA_9")
    assert_series_equal(ema_series(closes, 21), series["EMA_21"], "EMA_21")


def test_sma(golden):
    candles, _, series = golden
    closes = [c.close for c in candles]
    assert_series_equal(sma_series(closes, 14), series["SMA_14"], "SMA_14")


def test_rsi(golden):
    candles, _, series = golden
    closes = [c.close for c in candles]
    assert_series_equal(rsi_series(closes, 14), series["RSI_14"], "RSI_14")


def test_atr(golden):
    candles, _, series = golden
    assert_series_equal(atr_series(candles, 14), series["ATR_14"], "ATR_14")
    for smoothing in ("sma", "ema", "wma"):
        key = f"ATR_14_{smoothing.upper()}"
        assert_series_equal(atr_smoothed_series(candles, 14, smoothing), series[key], key)
    # rma delegates to the legacy path bit-for-bit
    assert atr_smoothed_series(candles, 14, "rma") == atr_series(candles, 14)


def test_volma(golden):
    candles, _, series = golden
    vols = [c.volume for c in candles]
    assert_series_equal(sma_series(vols, 20), series["VOLMA_20"], "VOLMA_20")


def test_sr_levels(golden):
    from auto_trader.indicators.sr_levels import SrConfig, sr_series

    candles, _, series = golden
    cfg = SrConfig(pivot_len=5, atr_mult=0.5, min_touches=2, max_levels=8, max_bars=500)
    for output, key in (("support", "SR_SUPPORT"), ("resistance", "SR_RESISTANCE")):
        expected = series[key]
        # Guard against a vacuous golden: the synthetic walk must form levels.
        assert any(v is not None for v in expected), f"{key}: golden is all-None"
        assert_series_equal(sr_series(cfg, output, candles, 1.0), expected, key)


def test_fvg(golden):
    from auto_trader.indicators.fvg import FvgConfig, fvg_series

    candles, _, series = golden
    cfg = FvgConfig(min_size=0.25, max_bars=500, max_gaps=10)
    for output, key in (
        ("bull_top", "FVG_BULL_TOP"),
        ("bull_bottom", "FVG_BULL_BOTTOM"),
        ("bear_top", "FVG_BEAR_TOP"),
        ("bear_bottom", "FVG_BEAR_BOTTOM"),
    ):
        expected = series[key]
        # Guard against a vacuous golden: the synthetic walk must open gaps.
        assert any(v is not None for v in expected), f"{key}: golden is all-None"
        assert_series_equal(fvg_series(cfg, output, candles, 1.0), expected, key)


def test_trendlines(golden):
    from auto_trader.indicators.trendlines import TrendlinesConfig, trendlines_series

    candles, _, series = golden
    # Mirrors the generator config in indicatorParityGolden.test.ts VALUE FOR
    # VALUE. If the two drift, this compares two different indicators and
    # passes or fails for the wrong reason.
    cfg = TrendlinesConfig(
        pivot_len=3, viol_mult=0.25, touch_mult=0.75, min_touches=2,
        min_span_bars=10, max_proj_bars=60, break_hold_bars=30, max_lines=3,
        min_swing_atr=0.0, min_swing_reach=0, pair_pivots=20, max_touches=0, max_span_bars=0, max_slope_atr=0.0, min_slope_atr=0.0, min_back_bars=0,
    )
    for output, key in (
        ("tl_support", "TL_SUPPORT"),
        ("tl_resistance", "TL_RESISTANCE"),
        ("tl_broken_support", "TL_BROKEN_SUPPORT"),
        ("tl_broken_resistance", "TL_BROKEN_RESISTANCE"),
    ):
        expected = series[key]
        # Guard against a vacuous golden: the synthetic walk must form lines,
        # break them, and hold the broken ones. An all-None series would pass
        # against a port that returns nothing.
        assert any(v is not None for v in expected), f"{key}: golden is all-None"
        assert_series_equal(trendlines_series(cfg, output, candles, 1.0), expected, key)


def test_trendlines_min_swing_atr(golden):
    """The SAME config with the swing-size gate on.

    Not foldable into the series above: at min_swing_atr 0 the gate returns
    before it reads a bar, so a port with the arithmetic wrong still matches
    there. This is the only case that ports the cross-multiplied depth test.
    """
    from auto_trader.indicators.trendlines import TrendlinesConfig, trendlines_series

    candles, _, series = golden
    cfg = TrendlinesConfig(
        pivot_len=3, viol_mult=0.25, touch_mult=0.75, min_touches=2,
        min_span_bars=10, max_proj_bars=60, break_hold_bars=30, max_lines=3,
        min_swing_atr=2.0, min_swing_reach=0, pair_pivots=20, max_touches=0, max_span_bars=0, max_slope_atr=0.0, min_slope_atr=0.0, min_back_bars=0,
    )
    for output, key in (
        ("tl_support", "TL_SWING_SUPPORT"),
        ("tl_resistance", "TL_SWING_RESISTANCE"),
    ):
        expected = series[key]
        assert any(v is not None for v in expected), f"{key}: golden is all-None"
        # And it must differ from the ungated series, or the gate is inert and
        # this test would pass against a port that ignores min_swing_atr.
        base = series[key.replace("TL_SWING_", "TL_")]
        assert expected != base, f"{key}: identical to the ungated series"
        assert_series_equal(trendlines_series(cfg, output, candles, 1.0), expected, key)


def test_trendlines_min_swing_reach(golden):
    """The same config with the LEFT-REACH gate on. Separate for the same
    reason as the size gate: at 0 it returns before reading a bar. 12 bites
    where pivot_len 3 does not."""
    from auto_trader.indicators.trendlines import TrendlinesConfig, trendlines_series

    candles, _, series = golden
    cfg = TrendlinesConfig(
        pivot_len=3, viol_mult=0.25, touch_mult=0.75, min_touches=2,
        min_span_bars=10, max_proj_bars=60, break_hold_bars=30, max_lines=3,
        min_swing_atr=0.0, min_swing_reach=12, pair_pivots=20, max_touches=0, max_span_bars=0, max_slope_atr=0.0, min_slope_atr=0.0, min_back_bars=0,
    )
    for output, key in (
        ("tl_support", "TL_REACH_SUPPORT"),
        ("tl_resistance", "TL_REACH_RESISTANCE"),
    ):
        expected = series[key]
        assert any(v is not None for v in expected), f"{key}: golden is all-None"
        base = series[key.replace("TL_REACH_", "TL_")]
        assert expected != base, f"{key}: identical to the ungated series"
        assert_series_equal(trendlines_series(cfg, output, candles, 1.0), expected, key)


def test_trendlines_pair_pivots(golden):
    """The pairing window at 5 instead of 20. Unlike the two gates this param
    has no off switch to short-circuit, but the base series uses exactly the old
    hard-coded 20, so a port that ignored it entirely would still match there."""
    from auto_trader.indicators.trendlines import TrendlinesConfig, trendlines_series

    candles, _, series = golden
    cfg = TrendlinesConfig(
        pivot_len=3, viol_mult=0.25, touch_mult=0.75, min_touches=2,
        min_span_bars=10, max_proj_bars=60, break_hold_bars=30, max_lines=3,
        min_swing_atr=0.0, min_swing_reach=0, pair_pivots=5, max_touches=0, max_span_bars=0, max_slope_atr=0.0, min_slope_atr=0.0, min_back_bars=0,
    )
    for output, key in (
        ("tl_support", "TL_PAIR_SUPPORT"),
        ("tl_resistance", "TL_PAIR_RESISTANCE"),
    ):
        expected = series[key]
        assert any(v is not None for v in expected), f"{key}: golden is all-None"
        base = series[key.replace("TL_PAIR_", "TL_")]
        assert expected != base, f"{key}: identical to the default window"
        assert_series_equal(trendlines_series(cfg, output, candles, 1.0), expected, key)


def test_trendlines_max_touches(golden):
    """The touch CEILING, the mirror of min_touches. At 0 the gate
    short-circuits, so the base series proves nothing about it."""
    from auto_trader.indicators.trendlines import TrendlinesConfig, trendlines_series

    candles, _, series = golden
    cfg = TrendlinesConfig(
        pivot_len=3, viol_mult=0.25, touch_mult=0.75, min_touches=2,
        min_span_bars=10, max_proj_bars=60, break_hold_bars=30, max_lines=3,
        min_swing_atr=0.0, min_swing_reach=0, pair_pivots=20, max_touches=3, max_span_bars=0, max_slope_atr=0.0, min_slope_atr=0.0, min_back_bars=0,
    )
    for output, key in (
        ("tl_support", "TL_CAP_SUPPORT"),
        ("tl_resistance", "TL_CAP_RESISTANCE"),
    ):
        expected = series[key]
        assert any(v is not None for v in expected), f"{key}: golden is all-None"
        base = series[key.replace("TL_CAP_", "TL_")]
        assert expected != base, f"{key}: identical to the uncapped series"
        assert_series_equal(trendlines_series(cfg, output, candles, 1.0), expected, key)


def test_trendlines_max_span_bars(golden):
    """The span CEILING, the mirror of min_span_bars. At 0 it is inert, so the
    base series proves nothing about it."""
    from auto_trader.indicators.trendlines import TrendlinesConfig, trendlines_series

    candles, _, series = golden
    cfg = TrendlinesConfig(
        pivot_len=3, viol_mult=0.25, touch_mult=0.75, min_touches=2,
        min_span_bars=10, max_proj_bars=60, break_hold_bars=30, max_lines=3,
        min_swing_atr=0.0, min_swing_reach=0, pair_pivots=20, max_touches=0,
        max_span_bars=40, max_slope_atr=0.0, min_slope_atr=0.0, min_back_bars=0,
    )
    for output, key in (
        ("tl_support", "TL_SPAN_SUPPORT"),
        ("tl_resistance", "TL_SPAN_RESISTANCE"),
    ):
        expected = series[key]
        assert any(v is not None for v in expected), f"{key}: golden is all-None"
        base = series[key.replace("TL_SPAN_", "TL_")]
        assert expected != base, f"{key}: identical to the uncapped series"
        assert_series_equal(trendlines_series(cfg, output, candles, 1.0), expected, key)


def test_trendlines_max_slope_atr(golden):
    """The STEEPNESS ceiling. Inert at 0, so the base series covers none of it."""
    from auto_trader.indicators.trendlines import TrendlinesConfig, trendlines_series

    candles, _, series = golden
    cfg = TrendlinesConfig(
        pivot_len=3, viol_mult=0.25, touch_mult=0.75, min_touches=2,
        min_span_bars=10, max_proj_bars=60, break_hold_bars=30, max_lines=3,
        min_swing_atr=0.0, min_swing_reach=0, pair_pivots=20, max_touches=0,
        max_span_bars=0, max_slope_atr=0.1, min_slope_atr=0.0, min_back_bars=0,
    )
    for output, key in (
        ("tl_support", "TL_SLOPE_SUPPORT"),
        ("tl_resistance", "TL_SLOPE_RESISTANCE"),
    ):
        expected = series[key]
        assert any(v is not None for v in expected), f"{key}: golden is all-None"
        base = series[key.replace("TL_SLOPE_", "TL_")]
        assert expected != base, f"{key}: identical to the uncapped series"
        assert_series_equal(trendlines_series(cfg, output, candles, 1.0), expected, key)


def test_trendlines_min_slope_atr(golden):
    """The steepness FLOOR, which drops near-horizontal lines the ceiling keeps."""
    from auto_trader.indicators.trendlines import TrendlinesConfig, trendlines_series

    candles, _, series = golden
    cfg = TrendlinesConfig(
        pivot_len=3, viol_mult=0.25, touch_mult=0.75, min_touches=2,
        min_span_bars=10, max_proj_bars=60, break_hold_bars=30, max_lines=3,
        min_swing_atr=0.0, min_swing_reach=0, pair_pivots=20, max_touches=0,
        max_span_bars=0, max_slope_atr=0.0, min_slope_atr=0.05, min_back_bars=0,
    )
    for output, key in (
        ("tl_support", "TL_FLAT_SUPPORT"),
        ("tl_resistance", "TL_FLAT_RESISTANCE"),
    ):
        expected = series[key]
        assert any(v is not None for v in expected), f"{key}: golden is all-None"
        base = series[key.replace("TL_FLAT_", "TL_")]
        assert expected != base, f"{key}: identical to the unfloored series"
        assert_series_equal(trendlines_series(cfg, output, candles, 1.0), expected, key)


def test_trendlines_min_back_bars(golden):
    """The BACKWARD clearance gate: bars before the first anchor that must sit
    on the line's own side of it. Seeding never looked before i1, so a pair
    whose angle has nothing to do with the trend passed as long as its wrong
    side was in the past."""
    from auto_trader.indicators.trendlines import TrendlinesConfig, trendlines_series

    candles, _, series = golden
    cfg = TrendlinesConfig(
        pivot_len=3, viol_mult=0.25, touch_mult=0.75, min_touches=2,
        min_span_bars=10, max_proj_bars=60, break_hold_bars=30, max_lines=3,
        min_swing_atr=0.0, min_swing_reach=0, pair_pivots=20, max_touches=0,
        max_span_bars=0, max_slope_atr=0.0, min_slope_atr=0.0, min_back_bars=15,
    )
    for output, key in (
        ("tl_support", "TL_BACK_SUPPORT"),
        ("tl_resistance", "TL_BACK_RESISTANCE"),
    ):
        expected = series[key]
        assert any(v is not None for v in expected), f"{key}: golden is all-None"
        base = series[key.replace("TL_BACK_", "TL_")]
        assert expected != base, f"{key}: identical to the ungated series"
        assert_series_equal(trendlines_series(cfg, output, candles, 1.0), expected, key)


def test_avwap(golden):
    candles, anchor_ms, series = golden
    assert_series_equal(avwap_series(candles, anchor_ms), series["AVWAP"], "AVWAP")


def test_avwap_unplaced_anchor_is_blank(golden):
    candles, _, _ = golden
    assert avwap_series(candles, 0) == [None] * len(candles)
    # Anchor past the last bar -> all blank too.
    last_ms = int(candles[-1].time.timestamp() * 1000)
    assert avwap_series(candles, last_ms + 1) == [None] * len(candles)


def test_mtf_alignment(golden_raw):
    data = golden_raw
    base_times_ms = [c["time"] * 1000 for c in data["candles"]]
    htf = [
        Candle(
            time=datetime.fromtimestamp(c["time"], tz=timezone.utc),
            open=c["open"], high=c["high"], low=c["low"], close=c["close"], volume=c["volume"],
        )
        for c in data["htfCandles"]
    ]
    from auto_trader.indicators.mtf import align_htf_to_base

    htf_ema = ema_series([c.close for c in htf], 9)
    aligned = align_htf_to_base(base_times_ms, htf, htf_ema, 4 * 3600 * 1000)
    assert_series_equal(aligned, data["series"]["EMA_9@HOUR_4"], "EMA_9@HOUR_4")


def test_slope(golden):
    candles, _, series = golden
    from auto_trader.indicators.mtf import slope_of

    ema9 = ema_series([c.close for c in candles], 9)
    assert_series_equal(slope_of(ema9, 3, 1.0), series["EMA_9~3"], "EMA_9~3")


def test_edge_cases():
    assert ema_series([], 9) == []
    assert sma_series([1.0, 2.0], 0) == [None, None]
    assert rsi_series([1.0] * 5, 14) == [None] * 5  # n <= period -> all None
    assert atr_series([], 14) == []
